window.readingSamples={
  "narrative": {
    "description": "先看最常见的连续叙事：不依赖标题，区分对白、动作、重点和引用。",
    "markdown": "雨停在凌晨四点。\n\n站台尽头的灯还亮着，积水把它拉成一条晃动的白线。你收起伞，沿着屋檐往前走。鞋底偶尔踩过碎石，声音很轻，却能听见走廊另一头的回响。\n\n*她靠在售票窗旁，低头翻着一本边角卷起的记录簿。听见脚步，才把手指从纸页间抽出来。*\n\n<q>“你比约好的时间早了。”</q>\n\n<q>“睡不着。”</q>你看了一眼空荡的铁轨，<q>“车还来吗？”</q>\n\n她没有立刻回答。远处响了一声短促的金属碰撞，像有人把工具放在地上。**月台上明明没有其他人。**\n\n> 最后一班列车到站前，请留在黄线以内。\n>\n> ——候车室墙上的旧告示\n\n你重新读了一遍那句话。油墨已经褪色，只有“最后一班”四个字被人用铅笔描过，笔画比周围深了许多。玻璃后面没有时刻表，原本挂着钟的位置，只剩一个颜色稍浅的圆。\n\n*她合上记录簿，把它递到你手边。封皮有一点湿，摸起来很凉。*\n\n<q>“如果你听见广播，”</q>她说，<q>“先看着我。”</q>\n\n你想问为什么，但她已经转向轨道。黑暗里，一点很小的光正在缓慢靠近。\n\n---\n\n<small>这段文字为排版示例，不属于游戏剧情。对白使用酒馆常见的 q 元素演示。</small>"
  },
  "formats": {
    "description": "一篇连续的说明文，覆盖标题、引用、列表、代码、表格、图片及原生折叠。",
    "markdown": "# 雨后的巡查记录\n\n昨夜的降雨已经停止。今天的工作从旧站台开始：核对通行路线，整理遗留物品，并把尚未确认的情况单独记录。**先保留事实，再补充判断。**\n\n## 出发之前\n\n把简短的重点留在段落里。*补充说明稍微退后*，而 <q>“需要被听见的话”</q> 保持清楚。不要仅凭字体颜色判断记录的重要程度。\n\n> 请在通过积水路段前检查照明。若看不清地面，应返回最近的安全位置。\n>\n> > 补充：两人同行时，保持能直接交谈的距离。\n\n### 随身物品\n\n- **照明工具**：手电与一组备用电池。\n- **记录用品**：纸笔、路线图，以及装有旧照片的透明袋。\n  - 对照照片上的门牌与现场标记。\n  - 不确定的字迹保留原样，稍后再核对。\n- **雨具**：收起后放在外侧，避免打湿记录。\n\n### 处理顺序\n\n1. 检查入口和撤离路线。\n2. 记录异常的位置与时间。\n3. 回到站台后整理结果。\n\n## 记录与核对\n\n单条记录使用 `station_id` 关联位置。路径如 `archive/stations/east-platform/report.json` 可以留在正文里，不必独占一行。\n\n| 位置 | 观察结果 | 后续安排 |\n| :--- | :--- | :--- |\n| 东侧入口 | 地面仍有少量积水 | 午后复查排水口 |\n| 售票窗口 | 玻璃完整，纸张受潮 | 拍照后晾干记录 |\n| 候车长椅 | 两处固定件松动 | 完成标记，安排维护 |\n\n下面是一条示例数据。代码保留原始内容与缩进，较长的行会自动换行。\n\n```json\n{\n  \"station_id\": \"east-platform\",\n  \"status\": \"pending_review\",\n  \"note\": \"核对位置、现场照片与记录时间后，再更新该条目的检查状态。\",\n  \"attachments\": [\"archive/stations/east-platform/inspection/photos/2026-09-11/full-resolution/entrance-after-rain.jpg\"]\n}\n```\n\n<details><summary>查看补充记录</summary><p>有两条记录的时间尚未核准。暂时保留原始顺序，并在复查后追加说明。</p><ul><li>旧表盘停在四点十分。</li><li>墙边发现一张被雨水打湿的车票。</li></ul><details><summary>现场记录的原文</summary><p>“先不要替它填上一个时间。”</p></details></details>\n\n## 图像与说明\n\n<figure><img src=\"assets/reference-room.jpg\" alt=\"官方研发通讯中的会客室界面参考图\"><figcaption>图像样例 · 本地保存的终末地官方研发通讯参考。仅用于展示正文图像的比例与图注，不对应上方虚构巡查内容。</figcaption></figure>\n\n## 更多文字层级\n\n### 三级标题 · 一组说明\n\n把相关内容放在一起，避免每两句话都另起一个大标题。\n\n#### 四级标题 · 局部步骤\n\n局部步骤保持正文尺度，通过字重区分。\n\n##### 五级标题 · 补充信息\n\n补充层级仍需清楚可读。\n\n###### 六级标题 · 最细一层\n\n这是样张的最小标题，不代表需要在每条回复里用到六级结构。\n\n<p><u>下划线</u>用于原文已有标注；<del>已划去的记录</del>仍然可读；<mark>高亮内容</mark>仅在正文主动包含 mark 时出现。H<sub>2</sub>O 与 m<sup>2</sup>保留上下标。</p>\n\n更多说明见[本页的出发检查](#出发之前)。链接有持续可见的下划线，悬停和键盘焦点也能辨认。\n\n---\n\n**整理完成。** 未确认的信息保留待查状态。"
  },
  "stress": {
    "description": "长中文标题、不间断链接、宽表格、多层折叠与长代码，检查窄屏是否仍能阅读和操作。",
    "markdown": "# 关于雨后东侧站台入口临时封闭期间的通行安排与记录核对说明\n\n这是长内容样张。正文保留连续阅读节奏；特殊内容在自己的区域内处理宽度。\n\n## 一段长文\n\n清晨的风沿着站台穿过来，把屋檐下的水滴吹得很远。你顺着墙上的箭头走到入口，发现那里多了一块手写的提示牌。牌子没有落款，只在右下角记着一个日期。你把日期抄在纸上，再回头查看刚才经过的地方。玻璃映出半截屋檐，积水里浮着几片颜色很深的叶子。整个过程没有什么特别的声响，只有鞋底触到地面时，能听见自己的步子。这段较长的文字用于观察中文行距、段间距和长行阅读，不要求读者通过装饰符号寻找每一句话的重点。\n\n## 链接与长标识\n\n<a href=\"#宽表格\">https://example.invalid/archive/ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789/extended-inspection-record-without-natural-breaks</a>\n\n行内标识：`east_platform_inspection_archive_20260911_ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789`。\n\n## 宽表格\n\n| 记录编号 | 入口名称 | 检查时间 | 状态 | 拍摄位置 | 备注 |\n| --- | --- | --- | --- | --- | --- |\n| ST-EAST-20260911-0001 | 东侧站台主入口 | 2026-09-11 07:30 | 等待复查 | 屋檐下第三根立柱旁 | 地面少量积水，照明正常 |\n| ST-EAST-20260911-0002 | 候车室外侧通道 | 2026-09-11 07:45 | 已完成 | 售票窗口前方 | 通道可正常通行 |\n\n## 保留原始代码\n\n```text\n01  第一行必须保留在同一行，检查原有缩进与空格。\n02      second_level: east-platform/inspection/archive/ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789/end-of-line\n03  回到左侧后仍然能够看到编号。\n```\n\n## 嵌套与折叠\n\n1. 一级内容\n   - 二级内容，一条足够长的中文说明需要自然换行，并且第二行应当仍然与当前条目的文字起点对齐。\n     - 三级内容，保持合理缩进，不让窄屏只剩几个字。\n2. 下一条一级内容。\n\n<details><summary>这是一条较长的折叠标题，包含现场位置、检查日期和需要补充核对的说明</summary><p>展开后仍在同一张纸面中阅读。</p><details><summary>再看一层补充内容</summary><p>嵌套层级可以关闭，也可以使用键盘重新打开。</p></details></details>\n\n> 这是一段引用。\n>\n> > 这是引用中的引用，在窄屏里也应当保留足够的阅读宽度。\n\n<p><label><input type=\"checkbox\" disabled checked>已核对原始记录</label><br><label><input type=\"checkbox\" disabled>待补充现场照片</label></p>\n\n---\n\n样张结束。"
  },
  "code": {
    "description": "查看内亮外淡的环面与四条斜向分界。可切换上版整圈环面，并展开奖励原图对照；长行自动换行，长代码纵向滚动，复制入口保持可见。",
    "markdown": "# 代码阅读\n\n代码放回自己的阅读区域：上方识别语言，下方查看内容。正文中的 `station_id` 仍是轻量的行内标记。\n\n## 脚本与注释\n\n```javascript\n// 根据状态整理待核对记录。\nfunction collectPending(records, stationId) {\n    const pending = records.filter(record => {\n        return record.station_id === stationId\n            && record.status === \"pending_review\";\n    });\n\n    return pending.map((record, index) => ({\n        id: record.id,\n        order: index + 1,\n        note: record.note ?? \"暂无补充说明\",\n        reviewed: false,\n    }));\n}\n\nconst result = collectPending(records, \"east-platform\");\nconsole.log(JSON.stringify(result, null, 2));\n```\n\n## 配置与长路径\n\n```json\n{\n  \"station_id\": \"east-platform\",\n  \"reviewed\": false,\n  \"attachments\": [\n    \"archive/stations/east-platform/inspection/photos/2026-09-11/full-resolution/entrance-after-rain.jpg\"\n  ],\n  \"note\": \"保留原始记录中的换行、缩进和路径。\"\n}\n```\n\n## 简短命令\n\n```bash\nnode inspect-records.js --station east-platform\n```\n\n## 纯文本输出\n\n```text\n[01] 入口记录已载入\n[02] 发现 2 条待核对记录\n[03] 保留原始文件，等待下一步处理\n```\n\n---\n以上代码只用于阅读样张。复制会取得原始代码，页面不会执行这些示例。"
  }
};
